export const API_ENDPOINTS = {
  BASE_URL: 'http://localhost:5001',
  TUTORS: '/api/v1/tutors',
  CONTENTS: '/api/v1/contents',
  IMAGES: '/img/',
  TEST_AUTH: '/api/v1/tutors/testAuth',
  REGISTER: '/api/v1/auth/register',
  LOGIN: '/api/v1/auth/login',
  LOGOUT: '/api/v1/auth/logout',
  REFRESH: '/api/v1/auth/refresh',
  REVIEWS: '/api/v1/reviews',
  CONTACTS: '/api/v1/contact',
  STATISTICS: '/statistics',
  GET_TUTOR: '/api/v1/tutors/byId/?id=',
  CONTACT: '/api/v1/contact/',
  GET_PROFILE: '/api/v1/user/byId/?id=',
  GET_TUTOR_USER: '/api/v1/tutors/byUser/?id=',
  UPDATE_PROFILE: '/api/v1/user/',
  UPDATE_TUTOR: '/api/v1/tutors/',
};
